package com.example.StageDIP.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;


@Entity
public class Fournisseur {

    // Primary key, auto-generated by the DB
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String nom;
    private String adresse;
    private String email;
    private Double notation;

    // Default constructor for JPA
    public Fournisseur() {}

    public Fournisseur(String nom, String adresse, String email, Double notation) {
        this.nom = nom;
        this.adresse = adresse;
        this.email = email;
        this.notation = notation;
    }

    // Getters & Setters

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getNom() { return nom; }
    public void setNom(String nom) { this.nom = nom; }

    public String getAdresse() { return adresse; }
    public void setAdresse(String adresse) { this.adresse = adresse; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public Double getNotation() { return notation; }
    public void setNotation(Double notation) { this.notation = notation; }
}
